import type { DropDownInfoDetailsProps } from "./components/DropDownInfoDetails";

export const mock: DropDownInfoDetailsProps[] = [
  {
    nome: "Fulano da Silva",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_1.pdf",
    oficio: "Nº 762/8GV-2025/SEI",
    processo: "Nº 6510.2025/0021921-2",
    estado: "SP",
    end: "Viaduto do Chá, 15, 12º andar – Centro",
    cep: "01020-900",
    descricao:
      "Galhos alcançando a fiação e bloqueando parcialmente a calçada. Solicito poda preventiva.",
    designacao: "Prefeitura Municipal de São Paulo",
  },
  {
    nome: "Maria Fernanda Souza",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_2.pdf",
    oficio: "Nº 815/2ZN-2025/SEI",
    processo: "Nº 6510.2025/0045312-7",
    estado: "SP",
    end: "Av. Paulista, 1578 – Bela Vista",
    cep: "01310-200",
    descricao:
      "Copa invadindo a rede elétrica e dificultando a passagem de pedestres. Requer poda.",
    designacao: "Subprefeitura Sé",
  },
  {
    nome: "João Pedro Albuquerque",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_3.pdf",
    oficio: "Nº 221/9VL-2025/SEI",
    processo: "Nº 6510.2025/0012345-6",
    estado: "SP",
    end: "Rua Vergueiro, 1000 – Liberdade",
    cep: "01504-001",
    descricao:
      "Galhos baixos atingindo transeuntes e próximos à sinalização. Solicito poda corretiva.",
    designacao: "Subprefeitura Sé",
  },
  {
    nome: "Ana Beatriz Rocha",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_4.pdf",
    oficio: "Nº 499/3SE-2025/SEI",
    processo: "Nº 6510.2025/0074521-0",
    estado: "SP",
    end: "Praça da Sé, 100 – Sé",
    cep: "01001-000",
    descricao:
      "Ramos sobre a fiação e risco de queda durante ventos fortes. Solicito poda urgente.",
    designacao: "Subprefeitura Sé",
  },
  {
    nome: "Carlos Eduardo Lima",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_5.pdf",
    oficio: "Nº 930/7PI-2025/SEI",
    processo: "Nº 6510.2025/0098765-4",
    estado: "SP",
    end: "Rua dos Pinheiros, 455 – Pinheiros",
    cep: "05422-011",
    descricao:
      "Copa avançando sobre marquise e rede aérea, obstruindo calçada. Requer poda preventiva.",
    designacao: "Subprefeitura Pinheiros",
  },
  {
    nome: "Patrícia Gomes",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_6.pdf",
    oficio: "Nº 312/1BR-2025/SEI",
    processo: "Nº 6510.2025/0006723-9",
    estado: "SP",
    end: "Av. Celso Garcia, 2200 – Brás",
    cep: "03015-000",
    descricao:
      "Galhos encostando na fiação e dificultando a visibilidade de placas. Solicito poda.",
    designacao: "Subprefeitura Mooca",
  },
  {
    nome: "Rafael Martins",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_7.pdf",
    oficio: "Nº 128/5IT-2025/SEI",
    processo: "Nº 6510.2025/0033988-1",
    estado: "SP",
    end: "Av. Brigadeiro Faria Lima, 3477 – Itaim Bibi",
    cep: "04538-133",
    descricao:
      "Ramos tangenciando cabos e avançando sobre a via. Solicito poda para segurança viária.",
    designacao: "Subprefeitura Pinheiros",
  },
  {
    nome: "Gabriela Nunes",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_8.pdf",
    oficio: "Nº 777/4CO-2025/SEI",
    processo: "Nº 6510.2025/0022788-3",
    estado: "SP",
    end: "Rua Augusta, 500 – Consolação",
    cep: "01305-000",
    descricao:
      "Copa muito densa sombreando iluminação pública e tocando a rede. Requer poda de manutenção.",
    designacao: "Subprefeitura Sé",
  },
  {
    nome: "Bruno Henrique Alves",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_9.pdf",
    oficio: "Nº 644/6SA-2025/SEI",
    processo: "Nº 6510.2025/0059874-2",
    estado: "SP",
    end: "Av. Sapopemba, 3500 – Sapopemba",
    cep: "03988-000",
    descricao:
      "Galhos invadindo calçada e atrapalhando passagem de cadeirantes. Solicito poda corretiva.",
    designacao: "Subprefeitura Sapopemba",
  },
  {
    nome: "Larissa Carvalho",
    solicitacao: "Poda de Árvore",
    status: "Enviado",
    file: "oficio_poda_10.pdf",
    oficio: "Nº 902/8PE-2025/SEI",
    processo: "Nº 6510.2025/0065432-8",
    estado: "SP",
    end: "Rua Heitor Penteado, 120 – Sumarezinho",
    cep: "05438-300",
    descricao:
      "Ramos sobre telhado de imóvel vizinho e próximos à rede elétrica. Solicito poda preventiva.",
    designacao: "Subprefeitura Pinheiros",
  },
];
